### ISSUE TITLE
download doesn't work

### ISSUE THREAD

**Issue by rubo77** [yclas/vagrant#4]
I can in stall the vagrant box and start it in the browser. the first step works, but then when I enter username and password 1234 and click "Continue" it redirects to index.php, which doesn't exist

**Comment by neo22s** [comment]
we will take a look thanks for reporting

**Comment by kotsios5** [comment]
@rubo77 This is now fixed, you can try starting from the step 3 https://github.com/open-classifieds/vagrant/blob/master/README.md

**Comment by rubo77** [comment]
Thx!
It works!
